name: Daily Job Alert

on:
  schedule:
    - cron: "0 8 * * *"   # Runs 12:00 Muscat (GMT+4)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Job Scraper
        env:
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: 465
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          MAIL_FROM: ${{ secrets.SMTP_USER }}
          TIMEZONE: Asia/Muscat
        run: python job_aggregator.py
